//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCH_Project.Dbconnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagerBySCHToDoListEntities1 : DbContext
    {
        public TaskManagerBySCHToDoListEntities1()
            : base("name=TaskManagerBySCHToDoListEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<Subtask> Subtask { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserTeam> UserTeam { get; set; }
    }
}
