//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCH_Project.DBconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeam
    {
        public int ID { get; set; }
        public Nullable<int> IdTeam { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
