//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCH_Project.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeam
    {
        public int ID { get; set; }
        public Nullable<int> IdTeam { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
